- type: job
  id: VKSCaptain
  name: job-name-vks-captain
  description: job-description-vks-captain
  playTimeTracker: JobVKSCaptain
  weight: 78
  startingGear: VKSCaptainGear
  alwaysUseSpawner: true
  icon: "JobIconPACTCaptain"
  requireAdminNotify: true
  supervisors: job-supervisors-rugov
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Russian
    - Esperanto
    languagesUnderstood:
    - Russian
    - Esperanto
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - PACT
    - type: ChatRank
      rank: BF-rank-ru-generalmajor
    - type: SurgerySpeedModifier
      SpeedModifier: 1.25
  - !type:AddImplantSpecial
    implants: [ TrackingImplantPACTRU ]
  access:
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  - PACTCommon
  - PACTCommand
  - PACTMaintenance
  - PACTSoldier
  - PACTArmory
  - PACTFunds
  - PACTCrew
  - PACTCaptain

- type: startingGear
  id: VKSCaptainGear
  equipment:
    id: VKSCaptainPDA
    ears: ClothingHeadsetAltRUCommand
    jumpsuit: ClothingUniformJumpsuitVKSCaptain
    shoes: ClothingShoesBootsJackFilled
#    back: ClothingBackpackSatchelSecurity
    belt: ClothingBeltCommandFilledRU
    gloves: ClothingHandsGlovesCombat
    pocket1: PouchFirstAidFilled
  storage:
    back:
    - ClothingMaskGasRussia
    - FlashlightMilitaryAlt
    - Tourniquet
    - Zipties
