- type: job
  id: MARSOCSquadLeader
  name: job-name-marsoc-squadleader
  description: job-description-marsoc-squadleader
  playTimeTracker: JobMARSOCSquadLeader
  weight: 78
  startingGear: MARSOCSquadLeaderGear
  alwaysUseSpawner: true
  icon: "JobIconNATOSquadleader"
  requireAdminNotify: false
  supervisors: job-supervisors-usgov
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - English
    - Esperanto
    languagesUnderstood:
    - English
    - Esperanto
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - USMC
    - type: ChatRank
      rank: BF-rank-us-gunnerysergeant
  - !type:AddImplantSpecial
    implants: [ TrackingImplantNATOUS ]
  access:
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  - NATOCommon
  - NATOCommand
  - NATOMaintenance
  - NATOMedical
  - NATOSoldier
  - NATOArmory
  - NATOFunds
  - NATOCrew
  - NATOCaptain

- type: startingGear
  id: MARSOCSquadLeaderGear
  equipment:
    id: MARSOCSquadLeaderPDA
    ears: ClothingHeadsetAltUSCommand
    neck: FlashlightMilitaryUS
    belt: ClothingBeltWebbingsNormalTanFilledSCARH
    jumpsuit: ClothingUniformJumpsuitCamoUSMarpatDesert
    head: ClothingHeadHatHelmetUSACH
    eyes: ClothingEyesGogglesTan
    balaclava: ClothingBalaclavaMilitary
    outerClothing: ClothingOuterArmorPlateCarrierIOTV
    shoes: ClothingShoesBootsJackFilledUSMC
    gloves: ClothingHandsGlovesCombat
    back: ClothingBackpackRucksackTan
    suitstorage: WeaponRifleBESCARH
    suitstorage2: WeaponShotgunUSM590
    pocket1: PouchMedkitFilledMarsoc
    pocket2: PouchGrenadesFilledUSMCRifleman
    leftarmband: Tourniquet
    rightarmband: ClothingArmbandThighHolsterFilledUSMK27
    wallet: ClothingWalletLeatherBlack
  storage:
    back:
    - ArmorPlateMediumPackaged
    - ShellBoxBF12GaugeBreaching
    - BoxMRE
    - ClothingMaskGasM40Green
    - MagazinePistolGlock17
    - MagazinePistolGlock17
    - CrowbarRed
    - Tourniquet
    - Zipties

- type: startingGear
  id: MARSOCSquadLeaderGearEVA
  equipment:
    id: MARSOCSquadLeaderPDA
    ears: ClothingHeadsetAltUS
    neck: FlashlightMilitaryUS
    belt: ClothingBeltWebbingsNormalBlackFilledSCARH
    jumpsuit: ClothingUniformJumpsuitCamoUSMarpatDesert
    eyes: ClothingEyesGogglesTan
    balaclava: ClothingBalaclavaMilitary
    outerClothing: ClothingOuterVoidsuitAmericanCombatMarine
    shoes: ClothingShoesBootsMagAshenFilled
    gloves: ClothingHandsGlovesCombat
    back: ClothingBackpackRucksackBlack
    suitstorage: WeaponRifleBESCARH
    suitstorage2: WeaponShotgunUSM590
    pocket1: PouchMedkitFilledMarsoc
    pocket2: PouchGrenadesFilledUSMCRifleman
    leftarmband: ClothingArmbandMassScanner
    rightarmband: ClothingArmbandThighHolsterFilledUSMK27
    wallet: ClothingWalletLeatherBlack
  storage:
    back:
    - ArmorPlateMediumPackaged
    - ShellBoxBF12GaugeBreaching
    - BoxMRE
    - ClothingMaskGasM40Green
    - MagazinePistolGlock17
    - MagazinePistolGlock17
    - DoubleEmergencyOxygenTankFilled
    - CrowbarRed
    - Tourniquet
    - Zipties

