- type: job
  id: MARSOCMedic
  name: job-name-marsoc-medic
  description: job-description-marsoc-medic
  playTimeTracker: JobMARSOCMedic
  weight: 75
  startingGear: MARSOCMedicGear
  alwaysUseSpawner: true
  icon: "JobIconNATOMedic"
  requireAdminNotify: false
  supervisors: job-supervisors-usgov
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - English
    languagesUnderstood:
    - English
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - USMC
    - type: SurgerySpeedModifier
      SpeedModifier: 2.25
    - type: ChatRank
      rank: BF-rank-corporal
  - !type:AddImplantSpecial
    implants: [ TrackingImplantNATOUS ]
  access:
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  - NATOCommon
  - NATOCommand
  - NATOMaintenance
  - NATOMedical
  - NATOSoldier
  - NATOArmory
  - NATOFunds
  - NATOCrew
  - NATOCaptain

- type: startingGear
  id: MARSOCMedicGear
  equipment:
    id: MARSOCMedicPDA
    ears: ClothingHeadsetAltUS
    neck: FlashlightMilitaryUS
    belt: ClothingBeltMedicalEMTFilledBF14Hyposprays
    jumpsuit: ClothingUniformJumpsuitCamoUSMarpatDesert
    head: ClothingHeadHatHelmetUSACH
    eyes: ClothingEyesHudMedicalBF
    balaclava: ClothingBalaclavaMilitary
    outerClothing: ClothingOuterArmorPlateCarrierIOTV
    shoes: ClothingShoesBootsJackFilledUSMC
    gloves: ClothingHandsGlovesLatex
    back: ClothingBackpackRucksackTan
    suitstorage: WeaponSubmachinegunDEMP7
    pocket1: PouchMagsPistolLargeFilledMP7
    pocket2: PouchMedkitFilledMarsoc
    leftarmband: Tourniquet
    rightarmband: ClothingArmbandThighHolsterFilledUSMK27
    wallet: ClothingWalletLeatherBlack
  storage:
    back:
    - SupplyBoxMedicalFilled
    - DefibrillatorCompactBF
    - MedkitAdvancedFilled
    - BoxMRE
    - ClothingMaskGasM40Green
    - TelescopicShield
    - OmnimedTool
    - CrowbarRed
    - Tourniquet
    - Zipties

- type: startingGear
  id: MARSOCMedicGearEVA
  equipment:
    id: MARSOCMedicPDA
    ears: ClothingHeadsetAltUS
    neck: FlashlightMilitaryUS
    belt: ClothingBeltMedicalEMTFilledBF14Hyposprays
    jumpsuit: ClothingUniformJumpsuitCamoUSMarpatDesert
    eyes: ClothingEyesHudMedicalBF
    balaclava: ClothingBalaclavaMilitary
    outerClothing: ClothingOuterVoidsuitAmericanCombatMarine
    shoes: ClothingShoesBootsMagAshenFilled
    gloves: ClothingHandsGlovesCombat
    back: ClothingBackpackRucksackBlack
    suitstorage: WeaponSubmachinegunDEMP7
    pocket1: PouchMagsPistolLargeFilledMP7
    pocket2: PouchGrenadesFilledUSMCScout
    leftarmband: ClothingArmbandMassScanner
    rightarmband: ClothingArmbandThighHolsterFilledUSMK27
    wallet: ClothingWalletLeatherBlack
  storage:
    back:
    - SupplyBoxMedicalFilled
    - DefibrillatorCompactBF
    - MedkitAdvancedFilled
    - BoxMRE
    - TelescopicShield
    - OmnimedTool
    - CrowbarRed
    - ClothingMaskGasM40Green
    - DoubleEmergencyOxygenTankFilled
    - Tourniquet
