- type: job
  id: SuspectUS
  name: Suspect
  description: job-description-ind-civilian
  playTimeTracker: JobSuspectUS
  displayWeight: 10
  startingGear: SuspectUSGear
  alwaysUseSpawner: true
  icon: "JobIconUS"
#  supervisors: job-supervisors-everyone
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - English
    languagesUnderstood:
    - English
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - VDV
  access:
  - Maintenance

- type: startingGear
  id: SuspectUSGear
  equipment:
    neck: ClothingNeckIFFtapeRed
    ears: ClothingHeadsetAltScav
    belt: WeaponPistolDEUSP45
    outerClothing: ClothingOuterArmorPlateCarrierCivilian
    back: ClothingBackpackButtpack
    leftarmband: Tourniquet
    rightarmband: FlashlightMilitaryUS
    pocket1: PouchMagsPistolFilledUSP45
    pocket2: PouchFirstAidFilled
  storage:
    back:
    - MaterialWoodPlank
    - SandbagFull5
    - MagazineBox45ACP
    - BF14KnifeFlipTaticool
