- type: job
  id: USMCRifleman
  name: job-name-usmc-rifleman
  description: job-description-usmc-rifleman
  playTimeTracker: JobUSMCRifleman
  weight: 77
  startingGear: USMCRiflemanGear
  alwaysUseSpawner: true
  icon: "JobIconNATORifleman"
  requireAdminNotify: false
  supervisors: job-supervisors-usgov
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - English
    languagesUnderstood:
    - English
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - USMC
    - type: ChatRank
      rank: BF-rank-private
  - !type:AddImplantSpecial
    implants: [ TrackingImplantNATOUS ]
  access:
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  - NATOCommon
  - NATOMaintenance
  - NATOSoldier
  - NATOArmory

- type: startingGear
  id: USMCRiflemanGear
  equipment:
    id: USMCRiflemanPDA
    ears: ClothingHeadsetAltUS
    belt: ClothingBeltMilitaryWebbingUSFilledSTANAG
    jumpsuit: ClothingUniformJumpsuitCamoUSMarpatDesert
    head: ClothingHeadHatHelmetUSACH
    outerClothing: ClothingOuterArmorPlateCarrierIOTV
    shoes: ClothingShoesBootsJackFilledUSMC
    suitstorage: WeaponRifleUSM27IAR
    pocket1: PouchFirstAidFilled
    pocket2: PouchGrenadesFilledUSMCRifleman
  storage:
    back:
    - ArmorPlateMediumPackaged
    - ClothingMaskGasM40
    - FlashlightMilitaryUS
    - Tourniquet
    - Zipties
