- type: job
  id: USMCSquadLeader
  name: job-name-usmc-squadleader
  description: job-description-usmc-squadleader
  playTimeTracker: JobUSMCSquadLeader
  weight: 78
  startingGear: USMCSquadLeaderGear
  alwaysUseSpawner: true
  icon: "JobIconNATOSquadleader"
  requireAdminNotify: true
  supervisors: job-supervisors-usgov
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - English
    - Esperanto
    languagesUnderstood:
    - English
    - Esperanto
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - USMC
    - type: ChatRank
      rank: BF-rank-sergeant
  - !type:AddImplantSpecial
    implants: [ TrackingImplantNATOUS ]
  access:
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  - NATOCommon
  - NATOCommand
  - NATOMaintenance
  - NATOSoldier
  - NATOArmory

- type: startingGear
  id: USMCSquadLeaderGear
  equipment:
    id: USMCSquadLeaderPDA
    ears: ClothingHeadsetAltUS
    belt: ClothingBeltMilitaryWebbingUSFilledSTANAGTracerRed
    jumpsuit: ClothingUniformJumpsuitCamoUSMarpatDesert
    head: ClothingHeadHatHelmetUSACH
    outerClothing: ClothingOuterArmorPlateCarrierIOTV
    shoes: ClothingShoesBootsJackFilledUSMC
    suitstorage: WeaponRifleUSM27IAR
    pocket1: PouchFirstAidFilled
    pocket2: PouchGrenadesFilledUSMCRifleman
    rightarmband: ClothingArmbandThighHolsterFilledUS
  storage:
    back:
    - ArmorPlateMediumPackaged
    - BoxPinpointerUniversalNATO
    - ClothingMaskGasM40
    - FlashlightMilitaryUS
    - MagazinePistolM9
    - MagazinePistolM9
    - Whistle
    - Tourniquet
    - Zipties
