- type: job
  id: USMCMedic
  name: job-name-usmc-medic
  description: job-description-usmc-medic
  playTimeTracker: JobUSMCMedic
  weight: 75
  startingGear: USMCMedicGear
  alwaysUseSpawner: true
  icon: "JobIconNATOMedic"
  requireAdminNotify: false
  supervisors: job-supervisors-usgov
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - English
    languagesUnderstood:
    - English
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - USMC
    - type: ChatRank
      rank: BF-rank-us-lancecorporal
    - type: SurgerySpeedModifier
      SpeedModifier: 1.65
  - !type:AddImplantSpecial
    implants: [ TrackingImplantNATOUS ]
  access:
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  - Medical
  - NATOCommon
  - NATOMaintenance
  - NATOMedical
  - NATOSoldier
  - NATOArmory

- type: startingGear
  id: USMCMedicGear
  equipment:
    id: USMCMedicPDA
    ears: ClothingHeadsetAltUS
    belt: ClothingBeltMedicalEMTFilledBF14
    eyes: ClothingEyesHudMedicalBF
    jumpsuit: ClothingUniformJumpsuitCamoUSMarpatDesert
    head: ClothingHeadHatHelmetUSACH
    outerClothing: ClothingOuterArmorPlateCarrierIOTV
    shoes: ClothingShoesBootsJackFilledUSMC
    gloves: ClothingHandsGlovesLatex
    suitstorage: WeaponRifleUSM27IAR
    pocket1: PouchMagsLargeFilledSTANAG
    pocket2: PouchGrenadesFilledUSMCScout
  inhand:
    - PaperWrittenManualCombatMedic
  storage:
    back:
    - SupplyBoxMedicalFilled
    - DefibrillatorCompactBF
    - ClothingMaskGasM40
    - FlashlightMilitaryUS
    - Tourniquet
    - Zipties
    - BiofoamCanisterRedDARPA
