- type: job
  id: HECUMedic
  name: job-name-hecu-medic
  description: job-description-hecu-medic
  playTimeTracker: JobHECUMedic
  weight: 75
  startingGear: HECUMedicGear
  alwaysUseSpawner: true
  icon: "JobIconNATOMedic"
  requireAdminNotify: false
  supervisors: job-supervisors-usgov
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - English
    languagesUnderstood:
    - English
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - USMC
    - type: SurgerySpeedModifier
      SpeedModifier: 1.65
    - type: ChatRank
      rank: BF-rank-corporal
  - !type:AddImplantSpecial
    implants: [ TrackingImplantNATOUS ]
  access:
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  - NATOCommon
  - NATOMaintenance
  - NATOMedical
  - NATOSoldier
  - NATOArmory

- type: startingGear
  id: HECUMedicGear
  equipment:
    id: HECUMedicPDA
    ears: ClothingHeadsetAltUS
    neck: FlashlightMilitaryUS
    belt: ClothingBeltMedicalEMTFilledBF14
    jumpsuit: ClothingUniformJumpsuitCamoUSM81UrbanHECU
    head: ClothingHeadHatHelmetUSUrban
    eyes: ClothingEyesHudMedicalBF
    outerClothing: ClothingOuterArmorPCV
    shoes: ClothingShoesBootsJackFilled
    gloves: ClothingHandsGlovesLatex
    back: ClothingBackpackMercenary
    suitstorage: WeaponSubmachinegunDEMP5A5
    pocket1: PouchMagsPistolLargeFilledMP5
    pocket2: PouchGrenadesFilledUSMCScout
    leftarmband: Tourniquet
    wallet: ClothingWalletLeatherBrown
  storage:
    back:
    - SupplyBoxMedicalFilled
    - DefibrillatorCompactBF
    - MedkitAdvancedFilled
    - CrowbarRed
    - ClothingMaskGasM40
    - PillCanisterHyronalin
    - Tourniquet
    - Zipties
    - BiofoamCanisterRedDARPA
