- type: job
  id: HECURifleman
  name: job-name-hecu-rifleman
  description: job-description-hecu-rifleman
  playTimeTracker: JobHECURifleman
  weight: 77
  startingGear: HECURiflemanGear
  alwaysUseSpawner: true
  icon: "JobIconNATORifleman"
  requireAdminNotify: false
  supervisors: job-supervisors-usgov
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - English
    languagesUnderstood:
    - English
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - USMC
    - type: ChatRank
      rank: BF-rank-private
  - !type:AddImplantSpecial
    implants: [ TrackingImplantNATOUS ]
  access:
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  - NATOCommon
  - NATOMaintenance
  - NATOSoldier
  - NATOArmory
  - PillHyronalin

- type: startingGear
  id: HECURiflemanGear
  equipment:
    id: HECURiflemanPDA
    ears: ClothingHeadsetAltUS
    neck: FlashlightMilitaryUS
    belt: ClothingBeltMilitaryWebbingUSFilledSTANAG
    jumpsuit: ClothingUniformJumpsuitCamoUSM81UrbanHECU
    head: ClothingHeadHatHelmetUSUrban
#    eyes: ClothingEyesGogglesTan
    mask: ClothingMaskGasM40Green
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorPCV
    shoes: ClothingShoesBootsJackFilled
    back: ClothingBackpackMercenary
    suitstorage: WeaponRifleUSCAR15
    pocket1: PouchFirstAidFilled
    pocket2: PouchGrenadesFilledUSARifleman
    leftarmband: Tourniquet
    wallet: ClothingWalletLeatherBrown
  storage:
    back:
    - BoxFlare
    - BoxMRE
    - CrowbarRed
    - PowerCellPCV
    - Tourniquet
    - Zipties
