- type: job
  id: HECUSquadLeader
  name: job-name-hecu-squadleader
  description: job-description-hecu-squadleader
  playTimeTracker: JobHECUSquadLeader
  weight: 78
  startingGear: HECUSquadLeaderGear
  alwaysUseSpawner: true
  icon: "JobIconNATOSquadleader"
  requireAdminNotify: false
  supervisors: job-supervisors-usgov
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - English
    - Esperanto
    languagesUnderstood:
    - English
    - Esperanto
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - USMC
    - type: ChatRank
      rank: BF-rank-sergeant
  - !type:AddImplantSpecial
    implants: [ TrackingImplantNATOUS ]
  access:
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  - NATOCommon
  - NATOCommand
  - NATOMaintenance
  - NATOSoldier
  - NATOArmory

- type: startingGear
  id: HECUSquadLeaderGear
  equipment:
    id: USMCSquadLeaderPDA
    ears: ClothingHeadsetAltUS
    neck: FlashlightMilitaryUS
    belt: ClothingBeltMilitaryWebbingUSFilledSTANAGTracerRed
    jumpsuit: ClothingUniformJumpsuitCamoUSM81UrbanHECU
    head: ClothingHeadHatBeret
#    eyes: ClothingEyesGogglesTan
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorPCV
    shoes: ClothingShoesBootsJackFilled
    back: ClothingBackpackMercenary
    suitstorage: WeaponRifleUSCAR15
    pocket1: PouchFirstAidFilled
    pocket2: PouchGrenadesFilledUSARifleman
    rightarmband: ClothingArmbandThighHolsterFilledUS
    leftarmband: Tourniquet
    wallet: ClothingWalletLeatherBrown
  storage:
    back:
    - WeaponCapacitorRechargerFlatpack
    - BoxMRE
    - CrowbarRed
    - MagazinePistolM9
    - MagazinePistolM9
    - PowerCellPCV
    - ClothingMaskGasM40
    - Tourniquet
    - Zipties
    - PillHyronalin