- type: job
  id: HECUSupport
  name: job-name-hecu-support
  description: job-description-hecu-support
  playTimeTracker: JobHECUSupport
  weight: 76
  startingGear: HECUSupportGear
  alwaysUseSpawner: true
  icon: "JobIconNATOEngineer"
  requireAdminNotify: false
  supervisors: job-supervisors-usgov
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - English
    languagesUnderstood:
    - English
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - USMC
    - type: ChatRank
      rank: BF-rank-corporal
  - !type:AddImplantSpecial
    implants: [ TrackingImplantNATOUS ]
  access:
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  - NATOCommon
  - NATOMaintenance
  - NATOSoldier
  - NATOArmory

- type: startingGear
  id: HECUSupportGear
  equipment:
    id: HECUSupportPDA
    ears: ClothingHeadsetAltUS
    neck: FlashlightMilitaryUS
    belt: ClothingBeltMilitaryWebbingUSFilled12GaugeBuckSlugBreach
    jumpsuit: ClothingUniformJumpsuitCamoUSM81UrbanHECU
    balaclava: ClothingBalaclavaMilitary
    eyes: ClothingEyesGogglesGreen
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorPCV
    shoes: ClothingShoesBootsJackFilled
    back: ClothingBackpackMercenary
    suitstorage: WeaponShotgunUSSPAS12
    pocket1: PouchFirstAidFilled
    pocket2: PouchGrenadesFilledUSARifleman
    leftarmband: Tourniquet
    wallet: ClothingWalletLeatherBrown
  storage:
    back:
    - SupplyBoxAmmoUSFilled
    - BoxMRE
    - ClothingMaskGasM40
    - CrowbarRed
    - WelderIndustrial
    - Wrench
    - Screwdriver
    - Wirecutter
    - Multitool
    - Zipties
    - PillHyronalin

- type: startingGear
  id: HECUSupportM249Gear
  equipment:
    id: HECUSupportPDA
    ears: ClothingHeadsetAltUS
    neck: FlashlightMilitaryUS
    belt: ClothingBeltMilitaryWebbingUSFilledM249
    jumpsuit: ClothingUniformJumpsuitCamoUSM81UrbanHECU
    balaclava: ClothingBalaclavaMilitary
    eyes: ClothingEyesGogglesGreen
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorPCV
    shoes: ClothingShoesBootsJackFilled
    back: ClothingBackpackMercenary
    suitstorage: WeaponMachineGunUSM249Para
    pocket1: PouchFirstAidFilled
    pocket2: PouchGrenadesFilledUSARifleman
    leftarmband: Tourniquet
    rightarmband: ClothingArmbandThighHolsterFilledUS
    wallet: ClothingWalletLeatherBrown
  storage:
    back:
    - SupplyBoxAmmoUSFilled
    - BoxMRE
    - ClothingMaskGasM40
    - CrowbarRed
    - WelderIndustrial
    - Tourniquet
    - Zipties
    - PillHyronalin

- type: startingGear
  id: HECUSupportSMAWGear
  equipment:
    id: HECUSupportPDA
    ears: ClothingHeadsetAltUS
    neck: FlashlightMilitaryUS
    belt: ClothingBeltMilitaryWebbingUS
    jumpsuit: ClothingUniformJumpsuitCamoUSM81UrbanHECU
    balaclava: ClothingBalaclavaMilitary
    eyes: ClothingEyesGogglesGreen
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorPCV
    shoes: ClothingShoesBootsJackFilled
    back: ClothingBackpackSatchelSecurity
    suitstorage: WeaponLauncherUSSMAW
    suitstorage2: WeaponSubmachinegunDEMP5A5
    pocket1: PouchMagsPistolLargeFilledMP5
    pocket2: PouchFirstAidFilled
    leftarmband: Tourniquet
    rightarmband: Tourniquet
    wallet: ClothingWalletLeatherBrown
  storage:
    back:
    - CartridgeSMAWNE
    - CartridgeSMAWNE
    - CartridgeSMAWHEDM
    - CartridgeSMAWHEDM
    belt:
    - BoxMRE
    - ClothingMaskGasM40
    - CrowbarRed
    - Tourniquet
    - Zipties
    - PillHyronalin