- type: job
  id: USSFCrewman
  name: job-name-ussf-crewman
  description: job-description-ussf-crewman
  playTimeTracker: JobUSSFCrewman
  weight: 77
  startingGear: USSFCrewmanGear
  alwaysUseSpawner: true
  icon: "JobIconNATOEngineer"
  requireAdminNotify: false
  supervisors: job-supervisors-usgov
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - English
    languagesUnderstood:
    - English
  - !type:AddImplantSpecial
    implants: [ TrackingImplantNATOUS ]
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - NATO
    - type: ChatRank
      rank: BF-rank-us-specialist2
    - type: SurgerySpeedModifier
      SpeedModifier: 1.25
  access:
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  - NATOCommon
  - NATOCommand
  - NATOMaintenance
  - NATOMedical
  - NATOArmory
  - NATOCrew

- type: startingGear
  id: USSFCrewmanGear
  equipment:
    id: USSFCrewmanPDA
    head: ClothingHeadHatBlacksoft
    ears: ClothingHeadsetAltUS
    jumpsuit: ClothingUniformJumpsuitSpaceForceCrewman
    shoes: ClothingShoesBootsJackFilledUSMC
#    back: ClothingBackpackSecurity
    belt: ClothingBeltAssaultFilledToolsSRD
    outerClothing: ClothingOuterArmorWebVestSec
    gloves: ClothingHandsGlovesCombat
    suitstorage: WeaponRifleUSM4
    pocket1: PouchMagsFilledSTANAG
    pocket2: PouchFirstAidFilled
  storage:
    back:
    - ClothingMaskGasM40
    - FlashlightMilitaryUS
    - ShipRepairDeviceAmmo
    - Tourniquet
    - Zipties
