- type: job
  id: USSFCaptain
  name: job-name-ussf-captain
  description: job-description-ussf-captain
  playTimeTracker: JobUSSFCaptain
  weight: 78
  startingGear: USSFCaptainGear
  alwaysUseSpawner: true
  icon: "JobIconNATOCaptain"
  requireAdminNotify: true
  supervisors: job-supervisors-usgov
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - English
    - Esperanto
    languagesUnderstood:
    - English
    - Esperanto
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - NATO
    - type: ChatRank
      rank: BF-rank-us-seniormastersergeant
    - type: SurgerySpeedModifier
      SpeedModifier: 1.25
    - type: CMVendorUser
      id: USSFLieutenant
      points: 4
  - !type:AddImplantSpecial
    implants: [ TrackingImplantNATOUS ]
  access:
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  - NATOCommon
  - NATOCommand
  - NATOMaintenance
  - NATOSoldier
  - NATOArmory
  - NATOFunds
  - NATOCrew
  - NATOCaptain

- type: startingGear
  id: USSFCaptainGear
  equipment:
    id: USSFCaptainPDA
    ears: ClothingHeadsetAltUSCommand
    jumpsuit: ClothingUniformJumpsuitSpaceForceCaptain
    shoes: ClothingShoesBootsJackFilledUSMC
#    back: ClothingBackpackSatchelSecurity
    belt: ClothingBeltCommandFilledUS
    gloves: ClothingHandsGlovesCombat
    pocket1: PouchFirstAidFilled
  storage:
    back:
    - CMVendUSSFWarVendorLieutenantTablet
    - ClothingMaskGasM40
    - FlashlightMilitaryUS
    - Tourniquet
    - Zipties
