- type: job
  id: PirateFirstMate
  name: job-name-pdv-asvaran
  description: job-description-pdv-asvaran
  playTimeTracker: JobPirateFirstMate
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 180000 # 50 hours
    - !type:RoleTimeRequirement
      role: JobPDVDenasvar
      time: 28800 # 8 hours
  startingGear: PirateFirstMateNFGear
  alwaysUseSpawner: true
  hideConsoleVisibility: true
  canBeAntag: true
  icon: "JobIconPirateFirstMate"
  supervisors: job-supervisors-pdv-vizier
  weight: 40
  displayWeight: 40
  assignedCompany: PDV
  setPreference: true
  access:
  - Pirate
  - PDVCommand
  - Mercenary
  accessGroups:
  - GeneralAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - PirateNF
  - !type:AddImplantSpecial
    implants: [ FreelanceTrackingImplant ]
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Freespeak
    languagesUnderstood:
    - Freespeak
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: PirateFirstMateNFGear
  equipment:
    ears: ClothingHeadsetAltVanguardCommand
    #belt: ClothingBeltUtility
    pocket1: BasePirateUplinkAsvaran
    #pocket2: AppraisalTool
  storage:
    back:
    - RadioHandheldNF
    - RubberStampPDVAsvaran
