- type: job
  id: PDVDenasvar
  name: job-name-pdv-denasvar
  description: job-description-pdv-denasvar
  playTimeTracker: JobPDVDenasvar
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 72000 # 20 hours
    - !type:RoleTimeRequirement
      role: JobPirate
      time: 36000 # 10 hours
  startingGear: PDVDenasvarGear
  alwaysUseSpawner: true
  hideConsoleVisibility: true
  canBeAntag: true
  icon: "JobIconPDVDenasvar"
  supervisors: job-supervisors-pdv-denasvar
  weight: 30
  displayWeight: 30
  assignedCompany: PDV
  setPreference: true
  access:
  - Pirate
  - PDVCommand
  - Mercenary
  accessGroups:
  - GeneralAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - PirateNF
  - !type:AddImplantSpecial
    implants: [ FreelanceTrackingImplant ]
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Freespeak
    languagesUnderstood:
    - Freespeak
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: PDVDenasvarGear
  equipment:
    ears: ClothingHeadsetAltVanguardCommand
    #belt: ClothingBeltUtility
    pocket1: BasePirateUplinkPirateCrew
    #pocket2: AppraisalTool
  storage:
    back:
    - RadioHandheldNF
