## NATO
#region US

- type: department
  id: USMC
  name: department-USMC-name
  description: department-USMC-description
  color: "#203564"
  weight: 85
  roles:
  - USMCLieutenant
  - USMCSquadLeader
  - USMCRifleman
  - USMCAutomaticRifleman
  - USMCMedic
  - USMCRecon

- type: department
  id: HECU
  name: department-HECU-name
  description: department-HECU-description
  color: "#203564"
  weight: 84
  roles:
  - HECUSquadLeader
  - HECURifleman
  - HECUSupport
  - HECUMedic

- type: department
  id: USSF
  name: department-USSF-name
  description: department-USSF-description
  color: "#203564"
  weight: 83
  roles:
  - USSFCaptain
  - USSFCrewman
  - USSFFighterPilot
  - USSFSquadLeader
  - USSFRifleman

- type: department
  id: ARNG
  name: department-NG-name
  description: department-NG-description
  color: "#203564"
  weight: 82
  roles:
  - NGLieutenant
  - NGSquadLeader
  - NGRifleman
  - NGAutomaticRifleman
  - NGMedic
  - NGRecon

- type: department
  id: USPD
  name: department-USPD-name
  description: department-USPD-description
  color: "#203564"
  weight: 45
  roles:
  - USPDChief
  - USPDWarden
  - USPDOfficer
  - USPDSWATLieutenant
  - USPDSWATSquadLeader
  - USPDSWATOfficer

#region DE

- type: department
  id: BW # Bundeswehr
  name: department-BW-name
  description: department-BW-description
  color: "#203564"
  weight: 75
  roles:
  - BWLieutenant
  - BWSquadLeader
  - BWRifleman
  - BWAutomaticRifleman
  - BWMedic
  - BWRecon

## PACT
#region RU

- type: department
  id: RGF
  name: department-RGF-name
  description: department-RGF-description
  color: "#a02829"
  weight: 66
  roles:
  - RGFLieutenant
  - RGFSquadLeader
  - RGFRifleman
  - RGFAutomaticRifleman
  - RGFMedic
  - RGFRecon

- type: department
  id: VDV
  name: department-VDV-name
  description: department-VDV-description
  color: "#a02829"
  weight: 65
  roles:
  - VDVLieutenant
  - VDVSquadLeader
  - VDVRifleman
  - VDVAutomaticRifleman
  - VDVMedic
  - VDVRecon

- type: department
  id: RKhB
  name: department-RKhB-name
  description: department-RKhB-description
  color: "#a02829"
  weight: 64
  roles:
  - RKhBSquadLeader
  - RKhBRifleman
  - RKhBSupport
  - RKhBMedic

- type: department
  id: FSB
  name: department-FSB-name
  description: department-FSB-description
  color: "#a02829"
  weight: 63
  roles:
  - FSBSquadLeader
  - FSBRifleman
  - FSBSupport
  - FSBMedic
  - FSBRecon
  editorHidden: true
  
- type: department
  id: VKS
  name: department-VKS-name
  description: department-VKS-description
  color: "#203564"
  weight: 64
  roles:
  - VKSCaptain
  - VKSCrewman
  - VKSFighterPilot

- type: department
  id: OMON
  name: department-OMON-name
  description: department-OMON-description
  color: "#203564"
  weight: 62
  roles:
  - OMONLieutenant # Unit Commander
  - OMONSquadLeader # Sergeant
  - OMONRifleman # Riot Officer

#region IND

- type: department
  id: WPS
  name: department-WPS-name
  description: department-WPS-description
  color: "#203564"
  weight: 50
  roles:
  - WPSSecurityOfficer
  - WPSWarden
  - WPSMarshal

- type: department
  id: BF14Civilian
  name: department-Civilian
  description: department-NFCivilian-description
  color: "#9FED58"
  weight: 1
  roles:
  - CivilianUS
  - CivilianRU
  - CivilianRUEMT
  - RUScav
  - RUScavGuard
  - RUScavBoss

#region Partisans against NATO

- type: department
  id: PartisanNATO
  name: Anti-NATO partisans
  description: department-NFCivilian-description
  color: "#9FED58"
  weight: 2
  roles:
  - SuspectUS
  - GRU90
  - Gypsy

#region Partisans against PACT

- type: department
  id: PartisanPACT
  name: Anti-PACT partisans
  description: department-NFCivilian-description
  color: "#9FED58"
  weight: 3
  roles:
  - Delta90
  - NationalistUA
