- type: department
  id: TDMBlue
  name: TDM (Blue)
  description: lorum ipsum
  color: "#203564"
  weight: 6
  roles:
  - TDMBlue

- type: job
  id: TDMBlue
  name: Blue Goon
  description: Shoot reds.
  playTimeTracker: JobTDMBlue
  displayWeight: 2
  startingGear: BF14TDMGearBlue
  alwaysUseSpawner: true
  icon: "JobIconNATORifleman"
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Blue
    - Esperanto
    languagesUnderstood:
    - Blue
    - Esperanto
  access:
  - Maintenance

- type: department
  id: TDMRed
  name: TDM (Red)
  description: lorum ipsum
  color: "#a02829"
  weight: 7
  roles:
  - TDMRed

- type: job
  id: TDMRed
  name: Red Goon
  description: Shoot blues.
  playTimeTracker: JobTDMRed
  displayWeight: 1
  startingGear: BF14TDMGearRed
  alwaysUseSpawner: true
  icon: "JobIconPACTRifleman"
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Red
    - Esperanto
    languagesUnderstood:
    - Red
    - Esperanto
  access:
  - Maintenance
