- type: job
  id: CrocusDockworker
  name: job-name-crocus-dockworker
  description: job-description-crocus-dockworker
  playTimeTracker: JobCrocusDockworker
  requirements:
  - !type:TraitsRequirement
    inverted: true
    traits:
    # Ironman gives you the LPC. The others are just free upgrades; Crocus has no bionics.
    - PrybarProsthetics
    - BionicLegs
    - Ironman
  startingGear: JianghuiDockworkerGear
  alwaysUseSpawner: true
  hideConsoleVisibility: true
  icon: "JobIconStationEngineer"
  supervisors: job-supervisors-nobody
  canBeAntag: false
  setPreference: true # For loadout.
  weight: 10
  displayWeight: 10
  accessGroups:
  - GeneralAccess
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - NovuNederic
    languagesUnderstood:
    - NovuNederic
    # TRUST
    removeLanguagesSpoken:
    - TauCetiBasic
    removeLanguagesUnderstood:
    - TauCetiBasic

- type: startingGear
  id: JianghuiDockworkerGear
  equipment:
    pocket1: RadioHandheldNF
    pocket2: FlashlightLantern
