- type: job
  id: OMONRifleman
  name: job-name-omon-rifleman
  description: job-description-omon-rifleman
  playTimeTracker: JobOMONRifleman
  weight: 71
  startingGear: OMONRiflemanGear
  alwaysUseSpawner: true
  icon: "JobIconPACTAllyRifleman"
  requireAdminNotify: false
  supervisors: job-supervisors-rugov
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Russian
    languagesUnderstood:
    - Russian
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - VDV
    - type: ChatRank
      rank: BF-rank-private
  - !type:AddImplantSpecial
    implants: [ TrackingImplantPACTRU ]
  access:
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  - PACTCommon
  - PACTMaintenance
  - PACTSoldier
  - PACTArmory

- type: startingGear
  id: OMONRiflemanGear
  equipment:
    id: OMONRiflemanPDA
    ears: ClothingHeadsetAltRU
    head: ClothingHeadHatHelmetRU6b47
    jumpsuit: ClothingUniformJumpsuitRUOMON
    outerClothing: ClothingOuterArmorWebVestSec
    belt: ClothingBeltMilitaryWebbingSmallPouchesOlive
    shoes: ClothingShoesBootsJackFilledRU
    pocket1: PouchFirstAidFilled
    pocket2: PouchGrenadesFilledVDVScout
  storage:
    back:
    - ArmorPlateLight
    - FlashlightMilitaryAlt
    - ClothingMaskGasRussia
    - Tourniquet
    - Zipties
