- type: job
  id: OMONSquadLeader
  name: job-name-omon-squadleader
  description: job-description-omon-squadleader
  playTimeTracker: JobOMONSquadLeader
  weight: 72
  startingGear: OMONSquadLeaderGear
  alwaysUseSpawner: true
  icon: "JobIconPACTAllySquadleader"
  requireAdminNotify: true
  supervisors: job-supervisors-rugov
  canBeAntag: false
  special:
  - !type:AddLanguageSpecial
    languagesSpoken:
    - Russian
    - Esperanto
    languagesUnderstood:
    - Russian
    - Esperanto
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - VDV
    - type: ChatRank
      rank: BF-rank-ru-juniorsergeant
  - !type:AddImplantSpecial
    implants: [ TrackingImplantPACTRU ]
  access:
  - Maintenance
  - Service
  - External
  - Mercenary # Frontier
  - Captain # Frontier
  - PACTCommon
  - PACTCommand
  - PACTMaintenance
  - PACTSoldier
  - PACTArmory

- type: startingGear
  id: OMONSquadLeaderGear
  equipment:
    id: OMONSquadLeaderPDA
    ears: ClothingHeadsetAltRUCommand
    head: ClothingHeadHatHelmetRU6b47
    jumpsuit: ClothingUniformJumpsuitRUOMON
    outerClothing: ClothingOuterArmorWebVestSec
    belt: ClothingBeltMilitaryWebbingSmallPouchesOlive
    shoes: ClothingShoesBootsJackFilledRU
    pocket1: PouchFirstAidFilled
    pocket2: PouchGrenadesFilledVDVScout
    rightarmband: ClothingArmbandThighHolsterFilledRU
  storage:
    back:
    - ArmorPlateLight
    - BoxPinpointerUniversalPACT
    - MagazinePistolMP443
    - MagazinePistolMP443
    - FlashlightMilitaryAlt
    - ClothingMaskGasRussia
    - SyndicateWhistle
    - Tourniquet
    - Zipties
