- type: entity
  id: BaseBulletPistol
  name: bullet
  parent: BaseBullet
  abstract: true
  categories: [ HideSpawnMenu ]
  components:
  - type: Sprite
    sprite: _Battlefield14/Objects/Weapons/Guns/Projectiles/ballistic.rsi
    layers:
    - state: small
  - type: Projectile
    damage:
      types:
        Piercing: 20
  - type: ProjectileDamageFalloff
    falloffStart: 6
    falloffPerTile: 0.1
    minimumMultiplier: 0.7
    stepByTile: true
  - type: StaminaDamageOnCollide
    damage: 5 # 20 hits to stun lol
  - type: Ammo
    muzzleFlash: MuzzleFlashEffectSmall

- type: entity
  id: BaseBulletPDW
  name: bullet
  parent: BaseBullet
  abstract: true
  categories: [ HideSpawnMenu ]
  components:
  - type: Sprite
    sprite: _Battlefield14/Objects/Weapons/Guns/Projectiles/ballistic.rsi
    layers:
    - state: small
  - type: Projectile
    damage:
      types:
        Piercing: 20
    armorPenetration: 0.3
  - type: ProjectileDamageFalloff
    falloffStart: 8
    falloffPerTile: 0.1
    minimumMultiplier: 0.85
    stepByTile: true
  - type: StaminaDamageOnCollide
    damage: 4 # 25 hits to stun lol
  - type: ArmorPiercing
    piercingThickness: 1
  - type: Ammo
    muzzleFlash: MuzzleFlashEffectSmall

- type: entity
  id: BaseBulletIntermediate
  name: bullet
  parent: BaseBullet
  abstract: true
  categories: [ HideSpawnMenu ]
  components:
  - type: Sprite
    sprite: _Battlefield14/Objects/Weapons/Guns/Projectiles/ballistic.rsi
    layers:
    - state: intermediate
  - type: Projectile
    damage:
      types:
        Piercing: 25
#    armorPenetration: 0.1
  - type: StaminaDamageOnCollide
    damage: 7 # ~15 hits to stun
  - type: ArmorPiercing
    piercingThickness: 2

- type: entity
  id: BaseBulletRifle
  name: bullet
  parent: BaseBullet
  abstract: true
  categories: [ HideSpawnMenu ]
  components:
  - type: Sprite
    sprite: _Battlefield14/Objects/Weapons/Guns/Projectiles/ballistic.rsi
    layers:
    - state: rifle
  - type: Projectile
    damage:
      types:
        Piercing: 30
  - type: StaminaDamageOnCollide
    damage: 8 # ~13 hits to stun
  - type: ArmorPiercing
    piercingThickness: 3

- type: entity
  id: BaseTracerRed
  name: bullet
  parent: BaseBullet
  abstract: true
  categories: [ HideSpawnMenu ]
  components:
  - type: PointLight
    radius: 2
    color: red
    energy: 1.6
  - type: Tracer
    color: red
    length: 3

- type: entity
  id: BaseTracerGreen
  name: bullet
  parent: BaseBullet
  abstract: true
  categories: [ HideSpawnMenu ]
  components:
  - type: PointLight
    radius: 2
    color: green
    energy: 1.6
  - type: Tracer
    color: lime
    length: 3
