## NATO
#region US
- type: entity
  id: CrateSecgearNATOFilledM249Para
  suffix: Filled, M249 Para
  parent: CrateSecgear
  name: M249 Para crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponMachineGunUSM249Para
          amount: 2
        - id: MagazineBeltBoxM249
          amount: 4
  - type: AccessReader
    access: [["NATOSoldier"]]

- type: entity
  id: CrateSecgearNATOFilledM240B
  suffix: Filled, M240B
  parent: CrateSecgear
  name: M240B crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponMachineGunUSM240B
          amount: 2
        - id: MagazineBeltBoxM240
          amount: 4
  - type: AccessReader
    access: [["NATOSoldier"]]

- type: entity
  id: CrateSecgearNATOFilledSMAW
  suffix: Filled, SMAW
  parent: CrateSecgear
  name: SMAW crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponLauncherUSSMAW
          amount: 2
        - id: CartridgeSMAWHEAA
          amount: 2
        - id: CartridgeSMAWNE
          amount: 2
        - id: CartridgeSMAWHEDM
          amount: 2
  - type: AccessReader
    access: [["NATOSoldier"]]

- type: entity
  id: CrateSecgearNATOFilledCarlGustavM2
  suffix: Filled, M2 Carl Gustav
  parent: CrateSecgear
  name: Carl Gustav M2 crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponLauncherSECarlGustavM2
          amount: 2
        - id: CartridgeCarlGustavHEDP502
          amount: 2
        - id: CartridgeCarlGustavHE441D
          amount: 2
  - type: AccessReader
    access: [["NATOSoldier"]]

- type: entity
  id: CrateSecgearNATOFilledAT4
  suffix: Filled, AT4
  parent: CrateSecgear
  name: AT4 crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponLauncherUSAT4
          amount: 2
  - type: AccessReader
    access: [["NATOSoldier"]]

- type: entity
  id: CrateSecgearNATOFilledSMAWDisposable
  suffix: Filled, SMAW-D
  parent: CrateSecgear
  name: SMAW-D crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponLauncherUSSMAWDisposableFolded
          amount: 2
  - type: AccessReader
    access: [["NATOSoldier"]]

- type: entity
  id: CrateSecgearNATOFilledM202FLASH
  suffix: Filled, M202 FLASH
  parent: CrateSecgear
  name: M202 FLASH crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponLauncherUSM202FLASHFolded
          amount: 2
  - type: AccessReader
    access: [["NATOSoldier"]]

- type: entity
  id: CrateSecgearNATOFilledM72LAW
  suffix: Filled, M72 LAW
  parent: CrateSecgear
  name: M72 LAW crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponLauncherUSM72LAWFolded
          amount: 5
  - type: AccessReader
    access: [["NATOSoldier"]]

- type: entity
  id: CrateSecgearNATOFilledM72LAWThermobaric
  suffix: Filled, M72 LAW, thermobaric
  parent: CrateSecgear
  name: thermobaric M72 LAW crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponLauncherUSM72LAWThermobaricFolded
          amount: 2
  - type: AccessReader
    access: [["NATOSoldier"]]

- type: entity
  id: CrateSecgearNATOFilledStinger
  suffix: Filled, Stinger
  parent: CrateSecgear
  name: FIM-92 Stinger MANPADS crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponLauncherUSStinger
          amount: 5
  - type: AccessReader
    access: [["NATOSoldier"]]

- type: entity
  id: CrateSecgearNATOFilledM27IAR
  suffix: Filled, M27IAR
  parent: CrateSecgear
  name: M27-IAR crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponRifleUSM27IAR
          amount: 5
        - id: BoxMagazineSTANAG
          amount: 2
  - type: AccessReader
    access: [["NATOSoldier"]]

- type: entity
  id: CrateSecgearNATOFilledM16A1
  suffix: Filled, M16A1
  parent: CrateSecgear
  name: M16A1 crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponRifleUSM16A1
          amount: 5
        - id: BoxMagazineSTANAGShort
          amount: 2
  - type: AccessReader
    access: [["NATOSoldier"]]

- type: entity
  id: CrateSecgearNATOFilledM16A2
  suffix: Filled, M16A2
  parent: CrateSecgear
  name: M16A2 crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponRifleUSM16A2
          amount: 5
        - id: BoxMagazineSTANAG
          amount: 2
  - type: AccessReader
    access: [["NATOSoldier"]]

- type: entity
  id: CrateSecgearNATOFilledM16A3
  suffix: Filled, M16A3
  parent: CrateSecgear
  name: M16A3 crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponRifleUSM16A3
          amount: 5
        - id: BoxMagazineSTANAG
          amount: 2
  - type: AccessReader
    access: [["NATOSoldier"]]

- type: entity
  id: CrateSecgearNATOFilledM16A4
  suffix: Filled, M16A4
  parent: CrateSecgear
  name: M16A4 crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponRifleUSM16A4
          amount: 5
        - id: BoxMagazineSTANAG
          amount: 2
  - type: AccessReader
    access: [["NATOSoldier"]]

- type: entity
  id: CrateSecgearNATOFilledM4A1
  suffix: Filled, M4A1
  parent: CrateSecgear
  name: M4A1 crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponRifleUSM4A1
          amount: 5
        - id: BoxMagazineSTANAG
          amount: 2
  - type: AccessReader
    access: [["NATOSoldier"]]

- type: entity
  id: CrateSecgearNATOFilledM870
  suffix: Filled, M870
  parent: CrateSecgear
  name: M870 crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponShotgunUSM870
          amount: 5
        - id: ShellBoxBF12GaugeBuckshot
          amount: 2
  - type: AccessReader
    access: [["NATOSoldier"]]

- type: entity
  id: CrateSecgearNATOFilledM590
  suffix: Filled, M590
  parent: CrateSecgear
  name: M590 crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponShotgunUSM590
          amount: 2
        - id: ShellBoxBF12GaugeBreaching
          amount: 2
  - type: AccessReader
    access: [["NATOSoldier"]]

- type: entity
  id: CrateSecgearNATOFilledM320
  suffix: Filled, M320
  parent: CrateSecgear
  name: M320 crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponGrenadeLauncherUSM320
        - id: BoxMagazine40x46HE
        - id: BoxMagazine40x46HEDP
        - id: BoxMagazine40x46Frag
        - id: BoxMagazine40x46ChemicalSmoke
        - id: BoxMagazine40x46mmIllumination
  - type: AccessReader
    access: [["NATOSoldier"]]

- type: entity
  id: CrateSecgearNATOFilledM320SWAT
  suffix: Filled, M320, SWAT
  parent: CrateSecgear
  name: M320 crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponGrenadeLauncherUSM320
        - id: BoxMagazine40x46ChemicalSmoke
        - id: BoxMagazine40x46mmIllumination
  - type: AccessReader
    access: [["NATOSoldier"]]

- type: entity
  id: CrateSecgearNATOFilledM14EBR
  suffix: Filled, Mk-14 EBR
  parent: CrateSecgear
  name: Mk-14 EBR crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponSniperUSM14EBR
          amount: 2
        - id: BoxMagazineM14
          amount: 2
  - type: AccessReader
    access: [["NATOSoldier"]]

- type: entity
  id: CrateSecgearNATOFilledM40A1
  suffix: Filled, M40A1
  parent: CrateSecgear
  name: M40A1 crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponSniperUSM40A1
          amount: 2
        - id: MagazineBox762x51
          amount: 2
  - type: AccessReader
    access: [["NATOSoldier"]]

- type: entity
  id: CrateSecgearNATOFilledSurplusM16
  suffix: Filled, surplus M16
  parent: CrateSecgear
  name: surplus M16 crate
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: BF14TableSurplusM16
        rolls: !type:RangeNumberSelector
          range: 5, 5
  - type: AccessReader
    access: [["NATOSoldier"]]

- type: entity
  id: CrateSecgearNATOFilledSCARH
  suffix: Filled, SCAR-H
  parent: CrateSecgear
  name: SCAR-H crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponRifleBESCARH
          amount: 5
        - id: BoxMagazineSCARH
          amount: 2
  - type: AccessReader
    access: [["NATOSoldier"]]

#region DE

- type: entity
  id: CrateSecgearNATOFilledG36
  suffix: Filled, G36
  parent: CrateSecgear
  name: G36 crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponRifleDEG36
          amount: 5
        - id: BoxMagazineG36
          amount: 2
  - type: AccessReader
    access: [["NATOSoldier"]]

- type: entity
  id: CrateSecgearNATOFilledMG3
  suffix: Filled, MG3
  parent: CrateSecgear
  name: MG3 crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponMachineGunDEMG3
          amount: 2
        - id: MagazineBeltBoxMG3Short
          amount: 8
  - type: AccessReader
    access: [["NATOSoldier"]]

- type: entity
  id: CrateSecgearNATOFilledMG36
  suffix: Filled, MG36
  parent: CrateSecgear
  name: MG36 crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponRifleDEMG36
          amount: 3
        - id: MagazineRifleG36DoubleDrumTracerRed
          amount: 6
  - type: AccessReader
    access: [["NATOSoldier"]]

- type: entity
  id: CrateSecgearNATOFilledPZF3
  suffix: Filled, panzerfaust-3
  parent: CrateSecgear
  name: panzerfaust-3 crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponLauncherDEPZF3
          amount: 2
        - id: CartridgePZF3HEAT
          amount: 2
        - id: CartridgePZF3HE
          amount: 2
  - type: AccessReader
    access: [["NATOSoldier"]]

- type: entity
  id: CrateSecgearNATOFilledG22A2
  suffix: Filled, G22A2
  parent: CrateSecgear
  name: G22A2 crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponSniperDEG22A2
          amount: 2
        - id: BoxMagazineAWM
          amount: 2
  - type: AccessReader
    access: [["NATOSoldier"]]

- type: entity
  id: CrateSecgearNATOFilledG28
  suffix: Filled, G28
  parent: CrateSecgear
  name: G28 crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponSniperDEG28
          amount: 2
        - id: BoxMagazineG28
          amount: 2
  - type: AccessReader
    access: [["NATOSoldier"]]

- type: entity
  id: CrateSecgearNATOFilledSurplusG3
  suffix: Filled, surplus G3
  parent: CrateSecgear
  name: surplus G3 crate
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: BF14TableSurplusG3
        rolls: !type:RangeNumberSelector
          range: 5, 5
  - type: AccessReader
    access: [["NATOSoldier"]]

## PACT
#region RU

- type: entity
  id: CrateSecgearPACTFilledAK12
  suffix: Filled, AK-12
  parent: CrateSecgear
  name: AK-12 crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponRifleRUAK12
          amount: 5
        - id: BoxMagazineAK12
          amount: 2
  - type: AccessReader
    access: [["PACTSoldier"]]

- type: entity
  id: CrateSecgearPACTFilledAK74
  suffix: Filled, AK-74
  parent: CrateSecgear
  name: AK-74 crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponRifleRUAK74
          amount: 5
        - id: BoxMagazineAK74
          amount: 2
  - type: AccessReader
    access: [["PACTSoldier"]]

- type: entity
  id: CrateSecgearPACTFilledAK74M
  suffix: Filled, AK-74M
  parent: CrateSecgear
  name: AK-74M crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponRifleRUAK74M
          amount: 5
        - id: BoxMagazineAK74Black
          amount: 2
  - type: AccessReader
    access: [["PACTSoldier"]]

- type: entity
  id: CrateSecgearPACTFilledAK203
  suffix: Filled, AK-203
  parent: CrateSecgear
  name: AK-203 crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponRifleRUAK203
          amount: 5
        - id: BoxMagazineAK203
          amount: 2
        - id: ClothingUniformJumpsuitCamoRUDigitalRed
          amount: 5
        - id: ClothingHelmetCoverRUDigitalRed
          amount: 5
  - type: AccessReader
    access: [["PACTSoldier"]]

- type: entity
  id: CrateSecgearPACTFilledRPK74
  suffix: Filled, RPK-74
  parent: CrateSecgear
  name: RPK-74 crate
  components:
  - type: StorageFill
    contents:
        - id: BF14WeaponCaseLongRURPK74
          amount: 3
  - type: AccessReader
    access: [["PACTSoldier"]]

- type: entity
  id: CrateSecgearPACTFilledRPK74M
  suffix: Filled, RPK-74M
  parent: CrateSecgear
  name: RPK-74M crate
  components:
  - type: StorageFill
    contents:
        - id: BF14WeaponCaseLongRURPK74M
          amount: 3
  - type: AccessReader
    access: [["PACTSoldier"]]

- type: entity
  id: CrateSecgearPACTFilledSV98
  suffix: Filled, SV-98
  parent: CrateSecgear
  name: SV-98 crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponSniperRUSV98
          amount: 2
        - id: BoxMagazineSV98
          amount: 2
  - type: AccessReader
    access: [["PACTSoldier"]]

- type: entity
  id: CrateSecgearPACTFilledSVDS
  suffix: Filled, SVDS
  parent: CrateSecgear
  name: SVDS crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponSniperRUSVDS
          amount: 2
        - id: BoxMagazineSVD
          amount: 2
  - type: AccessReader
    access: [["PACTSoldier"]]

- type: entity
  id: CrateSecgearPACTFilledKSK
  suffix: Filled, KSK
  parent: CrateSecgear
  name: KSK crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponShotgunRUKSK
          amount: 2
        - id: BoxMagazineKSKBuckshot
          amount: 2
        - id: BoxMagazineKSKSlug
  - type: AccessReader
    access: [["PACTSoldier"]]

- type: entity
  id: CrateSecgearPACTFilledPKM
  suffix: Filled, PKM
  parent: CrateSecgear
  name: PKM crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponMachineGunRUPKM
          amount: 2
        - id: MagazineBeltBoxPKM
          amount: 4
  - type: AccessReader
    access: [["PACTSoldier"]]

- type: entity
  id: CrateSecgearPACTFilledRPG7
  suffix: Filled, RPG-7
  parent: CrateSecgear
  name: RPG-7 crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponLauncherRURPG7
          amount: 2
        - id: CartridgeRPG7HEAT
          amount: 2
        - id: CartridgeRPG7Frag
          amount: 2
  - type: AccessReader
    access: [["PACTSoldier"]]

- type: entity
  id: CrateSecgearPACTFilledRPG30
  suffix: Filled, RPG-30
  parent: CrateSecgear
  name: RPG-30 crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponLauncherRURPG30
          amount: 2
  - type: AccessReader
    access: [["PACTSoldier"]]

- type: entity
  id: CrateSecgearPACTFilledRPG26
  suffix: Filled, RPG-26
  parent: CrateSecgear
  name: RPG-26 crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponLauncherRURPG26
          amount: 2
  - type: AccessReader
    access: [["PACTSoldier"]]

- type: entity
  id: CrateSecgearPACTFilledRPG26Thermobaric
  suffix: Filled, RShG-2
  parent: CrateSecgear
  name: RShG-2 crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponLauncherRURPG26Thermobaric
          amount: 2
  - type: AccessReader
    access: [["PACTSoldier"]]

- type: entity
  id: CrateSecgearPACTFilledRPOAShmel
  suffix: Filled, RPO-A Shmel
  parent: CrateSecgear
  name: RPO-A Shmel crate
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: BF14TableRPOAShmel
        rolls: !type:RangeNumberSelector
          range: 2, 2
  - type: AccessReader
    access: [["PACTSoldier"]]

- type: entity
  id: CrateSecgearPACTFilledIgla
  suffix: Filled, Igla
  parent: CrateSecgear
  name: Igla MANPADS crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponLauncherRUIgla
          amount: 5
  - type: AccessReader
    access: [["PACTSoldier"]]

- type: entity
  id: CrateSecgearPACTFilledKS23M
  suffix: Filled, KS-23M
  parent: CrateSecgear
  name: KS-23M crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponShotgunRUKS23M
          amount: 2
        - id: ShellBoxBF4GaugeShrap10
          amount: 4
        - id: ShellBoxBF4GaugeBarricade
          amount: 2
        - id: ShellBoxBF4GaugeShrap25
  - type: AccessReader
    access: [["PACTSoldier"]]

- type: entity
  id: CrateSecgearPACTFilledGM94
  suffix: Filled, GM-94
  parent: CrateSecgear
  name: GM-94 crate
  components:
  - type: StorageFill
    contents:
        - id: WeaponGrenadeLauncherRUGM94
        - id: BoxMagazine43x30HEFrag
        - id: BoxMagazine43x30Thermobaric
        - id: BoxMagazine43x30ChemicalSmoke
        - id: BoxMagazine43x30Illumination
  - type: AccessReader
    access: [["PACTSoldier"]]

## Misc
# Shared

- type: entity
  id: CrateSecgearFilledBarbwire
  suffix: Filled, barbed wire
  parent: CrateSecgear
  name: barbed wire coil crate
  components:
  - type: StorageFill
    contents:
        - id: BarbedWire10
          amount: 5
  - type: AccessReader
    access: [["NATOSoldier"] , ["PACTSoldier"]]
