- type: job
  id: Sheriff
  name: job-name-tsf-colonel
  description: job-description-tsf-colonel
  playTimeTracker: JobHeadOfSecurity
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 144000 # 40 hours
    - !type:DepartmentTimeRequirement
      department: Security
      time: 90000 # 25 hours
    - !type:RoleTimeRequirement
      role: JobWarden
      time: 18000 # 5 hours
  whitelisted: true
  startingGear: SheriffGear
  alwaysUseSpawner: true
  icon: JobIconSheriff
  requireAdminNotify: true
  supervisors: job-supervisors-tsf-ws
  weight: 180
  displayWeight: 70
  assignedCompany: TSF
  canBeAntag: false
  accessGroups:
  - AllAccessMono
  access:
  - TsfmcEngineering
  - HeadOfSecurity
  - Bailiff
  - Sergeant
  - Frontier
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - TSFMC
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  - !type:AddLanguageSpecial
    languagesSpoken:
    - SolCommon
    languagesUnderstood:
    - SolCommon
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: SheriffGear
  equipment:
    pocket1: WeaponEnergyGunMultiphase # DeltaV gun
    pocket2: EnergySwordNfsd
  storage:
    back:
    - Multitool
    - DoorRemoteNfsd
    - BaseSecurityUplinkRadioSheriff
    - ShipVoucherTsfmcColonel
    - PhoneInstrumentHigh
    - RubberStampTSFColonel
