- type: job
  id: Deputy
  name: job-name-tsf-marine
  description: job-description-tsf-marine
  playTimeTracker: JobSecurityOfficer
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 36000 # 10 hours
  startingGear: DeputyGear
  icon: JobIconDeputy
  supervisors: job-supervisors-tsf-ftl
  weight: 130
  displayWeight: 40
  assignedCompany: TSF
  canBeAntag: false
  accessGroups:
  - GeneralNfsdAccess
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - TSFMC
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]
  - !type:AddLanguageSpecial
    languagesSpoken:
    - SolCommon
    languagesUnderstood:
    - SolCommon
  - !type:GiveItemOnHolidaySpecial
    holiday: FrontierBirthday
    prototype: FrontierBirthdayGift

- type: startingGear
  id: DeputyGear
  equipment:
    pocket1: WeaponPistolMk58
  storage:
    back:
    - Magazine45_ACPPistolFMJ
    - BaseSecurityUplinkRadioDeputy
    - RadioHandheldNF
