#region US

#region USMC
- type: playTimeTracker
  id: JobUSMCLieutenant

- type: playTimeTracker
  id: JobUSMCSquadLeader

- type: playTimeTracker
  id: JobUSMCRifleman

- type: playTimeTracker
  id: JobUSMCAutomaticRifleman

- type: playTimeTracker
  id: JobUSMCMedic

- type: playTimeTracker
  id: JobUSMCRecon

#region USMC - MARSOC

- type: playTimeTracker
  id: JobMARSOCSquadLeader

- type: playTimeTracker
  id: JobMARSOCRifleman

- type: playTimeTracker
  id: JobMARSOCAutomaticRifleman

- type: playTimeTracker
  id: JobMARSOCMedic

#region USMC - HECU

- type: playTimeTracker
  id: JobHECUSquadLeader

- type: playTimeTracker
  id: JobHECURifleman

- type: playTimeTracker
  id: JobHECUSupport

- type: playTimeTracker
  id: JobHECUMedic

#region USSF

- type: playTimeTracker
  id: JobUSSFCaptain

- type: playTimeTracker
  id: JobUSSFCrewman

- type: playTimeTracker
  id: JobUSSFFighterPilot

- type: playTimeTracker
  id: JobUSSFSquadLeader

- type: playTimeTracker
  id: JobUSSFRifleman

#region National Guard

- type: playTimeTracker
  id: JobNGLieutenant

- type: playTimeTracker
  id: JobNGSquadLeader

- type: playTimeTracker
  id: JobNGRifleman

- type: playTimeTracker
  id: JobNGAutomaticRifleman

- type: playTimeTracker
  id: JobNGMedic

- type: playTimeTracker
  id: JobNGRecon

#region US Police

- type: playTimeTracker
  id: JobUSPDChief

- type: playTimeTracker
  id: JobUSPDWarden

- type: playTimeTracker
  id: JobUSPDOfficer

- type: playTimeTracker
  id: JobUSPDSWATLieutenant

- type: playTimeTracker
  id: JobUSPDSWATSquadLeader

- type: playTimeTracker
  id: JobUSPDSWATOfficer

#Region DE

#region BW

- type: playTimeTracker
  id: JobBWSquadLeader

- type: playTimeTracker
  id: JobBWRifleman

- type: playTimeTracker
  id: JobBWAutomaticRifleman

- type: playTimeTracker
  id: JobBWMedic

#region RU

#region RGF

- type: playTimeTracker
  id: JobRGFLieutenant

- type: playTimeTracker
  id: JobRGFSquadLeader

- type: playTimeTracker
  id: JobRGFRifleman

- type: playTimeTracker
  id: JobRGFAutomaticRifleman

- type: playTimeTracker
  id: JobRGFMedic

- type: playTimeTracker
  id: JobRGFRecon

#region VDV

- type: playTimeTracker
  id: JobVDVLieutenant

- type: playTimeTracker
  id: JobVDVSquadLeader

- type: playTimeTracker
  id: JobVDVRifleman

- type: playTimeTracker
  id: JobVDVAutomaticRifleman

- type: playTimeTracker
  id: JobVDVMedic

- type: playTimeTracker
  id: JobVDVRecon

#region RKhB

- type: playTimeTracker
  id: JobRKhBSquadLeader

- type: playTimeTracker
  id: JobRKhBRifleman

- type: playTimeTracker
  id: JobRKhBSupport

- type: playTimeTracker
  id: JobRKhBMedic

#region FSB

- type: playTimeTracker
  id: JobFSBSquadLeader

- type: playTimeTracker
  id: JobFSBRifleman

- type: playTimeTracker
  id: JobFSBSupport

- type: playTimeTracker
  id: JobFSBMedic

- type: playTimeTracker
  id: JobFSBRecon

#region VKS

- type: playTimeTracker
  id: JobVKSCaptain

- type: playTimeTracker
  id: JobVKSCrewman

- type: playTimeTracker
  id: JobVKSFighterPilot

#region OMON

- type: playTimeTracker
  id: JobOMONLieutenant # Unit Commander

- type: playTimeTracker
  id: JobOMONSquadLeader # Sergeant

- type: playTimeTracker
  id: JobOMONRifleman # Riot Officer

#region IND

#region Scav

- type: playTimeTracker
  id: JobRUScav

- type: playTimeTracker
  id: JobRUScavGuard

- type: playTimeTracker
  id: JobRUScavBoss

#region Western Private Security

- type: playTimeTracker
  id: JobWPSSecurityOfficer

- type: playTimeTracker
  id: JobWPSWarden

- type: playTimeTracker
  id: JobWPSMarshal

#region Partisan

- type: playTimeTracker
  id: JobSuspectUS

- type: playTimeTracker
  id: JobDelta90

- type: playTimeTracker
  id: JobGRU90

#region Civilian

- type: playTimeTracker
  id: JobCivilianUS

- type: playTimeTracker
  id: JobCivilianRU

- type: playTimeTracker
  id: JobCivilianRUEMT

- type: playTimeTracker
  id: JobNationalistUA

- type: playTimeTracker
  id: JobGypsy

#region Misc

- type: playTimeTracker
  id: JobTDMBlue

- type: playTimeTracker
  id: JobTDMred